name: notes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  # Firebase.
  firebase_core:
  cloud_firestore:
  firebase_auth: ^1.0.3
  readmore:
    git: 
      url: git://github.com/epynic/readmore
  flutter:
    sdk: flutter
  flutter_login: ^1.1.0
  flutter_rating_bar: ^4.0.0
  sqflite:
  path:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  bloc:
  bloc_test:
  equatable:
  flutter_bloc:
  flutter_colorpicker: ^0.3.5
  flutter_test:
    sdk: flutter
  flutter_swiper: ^1.1.6
  google_fonts:
  image_picker:
  mockito:
  path_provider:
  pedantic: ^1.9.0
  rxdart: ^0.25.0
  test:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/notes.json
    - assets/note_categories.json
    - assets/note_to_note_categories.json
    - assets/coffee_tastings.json
    - assets/coffee_tastings_notes.json
    - assets/images/coffee.jpg
    - assets/images/np_book.png
    - assets/images/np_grapes_small.png
    - assets/images/np_vinification.png
    - assets/images/np_library.png
    - assets/images/np_x.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Black.ttf
        - asset: assets/fonts/Jost-BlackItalic.ttf
        - asset: assets/fonts/Jost-Bold.ttf
        - asset: assets/fonts/Jost-BoldItalic.ttf
        - asset: assets/fonts/Jost-ExtraBold.ttf
        - asset: assets/fonts/Jost-ExtraBoldItalic.ttf
        - asset: assets/fonts/Jost-ExtraLight.ttf
        - asset: assets/fonts/Jost-ExtraLightItalic.ttf
        - asset: assets/fonts/Jost-Italic.ttf
        - asset: assets/fonts/Jost-Light.ttf
        - asset: assets/fonts/Jost-LightItalic.ttf
        - asset: assets/fonts/Jost-Medium.ttf
        - asset: assets/fonts/Jost-MediumItalic.ttf
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-SemiBold.ttf
        - asset: assets/fonts/Jost-SemiBoldItalic.ttf
        - asset: assets/fonts/Jost-Thin.ttf
        - asset: assets/fonts/Jost-ThinItalic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
