import 'package:flutter/material.dart';
import 'package:notes/src/data/constants.dart';
import 'package:notes/src/data/model/wine/varietal.dart';
import 'package:sqflite/sqflite.dart';

/// Varietals data access object for accessing the varietals table, enabling insertion and retrieval of varietals.
class VarietalDao {
  @required
  Future<Database> database;

  VarietalDao({this.database});

  /// Inserts a varietal. The input map must have a `"name"` field containing
  /// the name of the varietal. `"varietal_id"` is autogenerated and can be omitted.
  Future<int> insert(Map<String, dynamic> newVarietal) async {
    final db = await database;
    var res = await db.insert(VARIETALS_TABLE_NAME, newVarietal);
    return res;
  }

  /// Look up a varietal by id. If found, returns it as a [Varietal].
  Future<Varietal> get(int varietalId) async {
    final db = await database;

    var res = await db.rawQuery(
      // ignore: prefer_single_quotes
      """
        SELECT varietal_id, name
        FROM varietals
        WHERE varietal_id == $varietalId
        LIMIT 1
        """,
    );

    if (res.isNotEmpty) {
      return Varietal.fromAppDatabase(res.first);
    }

    return null;
  }

  /// Get all stored varietals as a list of [Varietal].
  Future<List<Varietal>> getAllVarietals() async {
    final db = await database;
    var res = await db.query(VARIETALS_TABLE_NAME);
    var list = res.isNotEmpty
        ? res.map((c) {
            return Varietal.fromAppDatabase(c);
          }).toList()
        : <Varietal>[];
    return list;
  }
}
